{% set name = "abi3info" %}
{% set version = "2024.9.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/abi3info-{{ version }}.tar.gz
  sha256: d8bd0ba81ee7cb37c8c46b9385e870b48570dc5118efc3c1bb1f8b696ebab0c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - abi3info
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/abi3info/
  summary: A library for abi3 and other CPython API information
  dev_url: https://github.com/woodruffw/abi3info
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
