{% set name = "abi3info" %}
{% set version = "2024.10.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/abi3info-{{ version }}.tar.gz
  sha256: b41fdf4f19e1b39d1e7d8269ad12d59a18d54c71601818ca61b1ed5a87341d13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - abi3info
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/abi3info/
  summary: A library for abi3 and other CPython API information
  dev_url: https://github.com/woodruffw/abi3info
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
