{% set name = "abi3info" %}
{% set version = "2025.11.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/abi3info-{{ version }}.tar.gz
  sha256: dd96754872211f96ed6955d47e725bdc579e581dd1705d581923270f825d1318

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - abi3info
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/abi3info/
  summary: A library for abi3 and other CPython API information
  dev_url: https://github.com/woodruffw/abi3info
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
